version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
